=== jaedon/freeview/apps/octo/service/obama/main/tvservice/pal/param/test/cutest_list.dtd
<!ELEMENT CUTEST_LIST_REPORT
  (CUTEST_HEADER, CUTEST_LIST_SUMMARY, CUTEST_LIST_ALL_TEST_LIST*, CUTEST_FOOTER)>

<!ELEMENT CUTEST_HEADER EMPTY>

<!ELEMENT CUTEST_LIST_SUMMARY (CUTEST_LIST_SUMMARY_RECORD*)>
  <!ELEMENT CUTEST_LIST_SUMMARY_RECORD
    (CUTEST_LIST_SUMMARY_RECORD_TEXT, CUTEST_LIST_SUMMARY_RECORD_VALUE)>
    <!ELEMENT CUTEST_LIST_SUMMARY_RECORD_TEXT (#PCDATA)>
    <!ELEMENT CUTEST_LIST_SUMMARY_RECORD_VALUE (#PCDATA)>

  <!ELEMENT CUTEST_LIST_TEST_CASE_DEFINITION (CUTEST_LIST_TEST_CASE_NAME?, CUTEST_LIST_TEST_ACTIVE_VALUE?, CUTEST_LIST_TEST_DESCRIPTION?)>
    <!ELEMENT CUTEST_LIST_TEST_CASE_NAME (#PCDATA)>
    <!ELEMENT CUTEST_LIST_TEST_ACTIVE_VALUE (#PCDATA)>
    <!ELEMENT CUTEST_LIST_TEST_DESCRIPTION (#PCDATA)>    

<!ELEMENT CUTEST_FOOTER (#PCDATA)>

=== jaedon/freeview/apps/octo/service/obama/main/tvservice/pal/param/test/pal_param_UnitaryTest_cutestList.xml
<?xml version="1.0" ?> 
<?xml-stylesheet type="text/xsl" href="cutest_list.xsl" ?> 
<!DOCTYPE CUTEST_LIST_REPORT SYSTEM "cutest_list.dtd"> 
<CUTEST_LIST_REPORT> 
  <CUTEST_HEADER/> 
  <CUTEST_LIST_SUMMARY> 
    <CUTEST_LIST_SUMMARY_RECORD> 
      <CUTEST_LIST_SUMMARY_RECORD_TEXT> Total Number of Test Cases </CUTEST_LIST_SUMMARY_RECORD_TEXT> 
      <CUTEST_LIST_SUMMARY_RECORD_VALUE> 1 </CUTEST_LIST_SUMMARY_RECORD_VALUE> 
    </CUTEST_LIST_SUMMARY_RECORD> 
  </CUTEST_LIST_SUMMARY> 
  <CUTEST_LIST_ALL_TEST_LIST> 
 	   <CUTEST_LIST_TEST_CASE_DEFINITION> 
 		 <CUTEST_LIST_TEST_CASE_NAME> pal_param_UtTestSet </CUTEST_LIST_TEST_CASE_NAME> 
 		 <CUTEST_LIST_TEST_ACTIVE_VALUE> Yes </CUTEST_LIST_TEST_ACTIVE_VALUE> 
 		 <CUTEST_LIST_TEST_DESCRIPTION>test
        </CUTEST_LIST_TEST_DESCRIPTION> 
 	   </CUTEST_LIST_TEST_CASE_DEFINITION> 
  </CUTEST_LIST_ALL_TEST_LIST> 
  <CUTEST_FOOTER> File Generated at Mon Dec  9 16:27:41 2013
 </CUTEST_FOOTER> 
</CUTEST_LIST_REPORT>
